// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.0
// source: mule.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Heartbeat messages
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_mule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{0}
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_mule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HeartbeatResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Provider messages
type ListProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersRequest) Reset() {
	*x = ListProvidersRequest{}
	mi := &file_mule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersRequest) ProtoMessage() {}

func (x *ListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{2}
}

type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*Provider            `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_mule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{3}
}

func (x *ListProvidersResponse) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

type Provider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_mule_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{4}
}

func (x *Provider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Workflow messages
type ListWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsRequest) Reset() {
	*x = ListWorkflowsRequest{}
	mi := &file_mule_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsRequest) ProtoMessage() {}

func (x *ListWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{5}
}

type ListWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*Workflow            `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsResponse) Reset() {
	*x = ListWorkflowsResponse{}
	mi := &file_mule_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsResponse) ProtoMessage() {}

func (x *ListWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{6}
}

func (x *ListWorkflowsResponse) GetWorkflows() []*Workflow {
	if x != nil {
		return x.Workflows
	}
	return nil
}

type GetWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowRequest) Reset() {
	*x = GetWorkflowRequest{}
	mi := &file_mule_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowRequest) ProtoMessage() {}

func (x *GetWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{7}
}

func (x *GetWorkflowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflow      *Workflow              `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowResponse) Reset() {
	*x = GetWorkflowResponse{}
	mi := &file_mule_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowResponse) ProtoMessage() {}

func (x *GetWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{8}
}

func (x *GetWorkflowResponse) GetWorkflow() *Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

type Workflow struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsDefault           bool                   `protobuf:"varint,4,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	Steps               []*WorkflowStep        `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	ValidationFunctions []string               `protobuf:"bytes,6,rep,name=validation_functions,json=validationFunctions,proto3" json:"validation_functions,omitempty"`
	Triggers            []*TriggerSettings     `protobuf:"bytes,7,rep,name=triggers,proto3" json:"triggers,omitempty"`
	Outputs             []*TriggerSettings     `protobuf:"bytes,8,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_mule_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{9}
}

func (x *Workflow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workflow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workflow) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Workflow) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Workflow) GetSteps() []*WorkflowStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Workflow) GetValidationFunctions() []string {
	if x != nil {
		return x.ValidationFunctions
	}
	return nil
}

func (x *Workflow) GetTriggers() []*TriggerSettings {
	if x != nil {
		return x.Triggers
	}
	return nil
}

func (x *Workflow) GetOutputs() []*TriggerSettings {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type WorkflowStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       int32                  `protobuf:"varint,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,3,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	OutputField   string                 `protobuf:"bytes,4,opt,name=output_field,json=outputField,proto3" json:"output_field,omitempty"`
	Integration   *TriggerSettings       `protobuf:"bytes,5,opt,name=integration,proto3" json:"integration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowStep) Reset() {
	*x = WorkflowStep{}
	mi := &file_mule_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStep) ProtoMessage() {}

func (x *WorkflowStep) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStep.ProtoReflect.Descriptor instead.
func (*WorkflowStep) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{10}
}

func (x *WorkflowStep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowStep) GetAgentId() int32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *WorkflowStep) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *WorkflowStep) GetOutputField() string {
	if x != nil {
		return x.OutputField
	}
	return ""
}

func (x *WorkflowStep) GetIntegration() *TriggerSettings {
	if x != nil {
		return x.Integration
	}
	return nil
}

type TriggerSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Integration   string                 `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSettings) Reset() {
	*x = TriggerSettings{}
	mi := &file_mule_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSettings) ProtoMessage() {}

func (x *TriggerSettings) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSettings.ProtoReflect.Descriptor instead.
func (*TriggerSettings) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{11}
}

func (x *TriggerSettings) GetIntegration() string {
	if x != nil {
		return x.Integration
	}
	return ""
}

func (x *TriggerSettings) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TriggerSettings) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

// Agent messages
type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_mule_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{12}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_mule_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{13}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_mule_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{14}
}

func (x *GetAgentRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_mule_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{15}
}

func (x *GetAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type Agent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProviderName   string                 `protobuf:"bytes,3,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	Model          string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	PromptTemplate string                 `protobuf:"bytes,5,opt,name=prompt_template,json=promptTemplate,proto3" json:"prompt_template,omitempty"`
	SystemPrompt   string                 `protobuf:"bytes,6,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Tools          []string               `protobuf:"bytes,7,rep,name=tools,proto3" json:"tools,omitempty"`
	UdiffSettings  *UDiffSettings         `protobuf:"bytes,8,opt,name=udiff_settings,json=udiffSettings,proto3" json:"udiff_settings,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_mule_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{16}
}

func (x *Agent) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *Agent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Agent) GetPromptTemplate() string {
	if x != nil {
		return x.PromptTemplate
	}
	return ""
}

func (x *Agent) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *Agent) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *Agent) GetUdiffSettings() *UDiffSettings {
	if x != nil {
		return x.UdiffSettings
	}
	return nil
}

type UDiffSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDiffSettings) Reset() {
	*x = UDiffSettings{}
	mi := &file_mule_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDiffSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDiffSettings) ProtoMessage() {}

func (x *UDiffSettings) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDiffSettings.ProtoReflect.Descriptor instead.
func (*UDiffSettings) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{17}
}

func (x *UDiffSettings) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// Running workflows messages
type ListRunningWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunningWorkflowsRequest) Reset() {
	*x = ListRunningWorkflowsRequest{}
	mi := &file_mule_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunningWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunningWorkflowsRequest) ProtoMessage() {}

func (x *ListRunningWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunningWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ListRunningWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{18}
}

type ListRunningWorkflowsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RunningWorkflows []*RunningWorkflow     `protobuf:"bytes,1,rep,name=running_workflows,json=runningWorkflows,proto3" json:"running_workflows,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListRunningWorkflowsResponse) Reset() {
	*x = ListRunningWorkflowsResponse{}
	mi := &file_mule_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunningWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunningWorkflowsResponse) ProtoMessage() {}

func (x *ListRunningWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunningWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ListRunningWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{19}
}

func (x *ListRunningWorkflowsResponse) GetRunningWorkflows() []*RunningWorkflow {
	if x != nil {
		return x.RunningWorkflows
	}
	return nil
}

type RunningWorkflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	WorkflowName  string                 `protobuf:"bytes,2,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	StepResults   []*WorkflowStepResult  `protobuf:"bytes,5,rep,name=step_results,json=stepResults,proto3" json:"step_results,omitempty"`
	CurrentStep   string                 `protobuf:"bytes,6,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunningWorkflow) Reset() {
	*x = RunningWorkflow{}
	mi := &file_mule_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningWorkflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningWorkflow) ProtoMessage() {}

func (x *RunningWorkflow) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningWorkflow.ProtoReflect.Descriptor instead.
func (*RunningWorkflow) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{20}
}

func (x *RunningWorkflow) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *RunningWorkflow) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *RunningWorkflow) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunningWorkflow) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *RunningWorkflow) GetStepResults() []*WorkflowStepResult {
	if x != nil {
		return x.StepResults
	}
	return nil
}

func (x *RunningWorkflow) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

type WorkflowStepResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowStepResult) Reset() {
	*x = WorkflowStepResult{}
	mi := &file_mule_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStepResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStepResult) ProtoMessage() {}

func (x *WorkflowStepResult) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStepResult.ProtoReflect.Descriptor instead.
func (*WorkflowStepResult) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{21}
}

func (x *WorkflowStepResult) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *WorkflowStepResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowStepResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WorkflowStepResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *WorkflowStepResult) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// Execute workflow messages
type ExecuteWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowName  string                 `protobuf:"bytes,1,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowRequest) Reset() {
	*x = ExecuteWorkflowRequest{}
	mi := &file_mule_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowRequest) ProtoMessage() {}

func (x *ExecuteWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowRequest.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{22}
}

func (x *ExecuteWorkflowRequest) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *ExecuteWorkflowRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ExecuteWorkflowRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ExecuteWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowResponse) Reset() {
	*x = ExecuteWorkflowResponse{}
	mi := &file_mule_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowResponse) ProtoMessage() {}

func (x *ExecuteWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mule_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowResponse.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_mule_proto_rawDescGZIP(), []int{23}
}

func (x *ExecuteWorkflowResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecuteWorkflowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteWorkflowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_mule_proto protoreflect.FileDescriptor

const file_mule_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"mule.proto\x12\amule.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x12\n" +
	"\x10HeartbeatRequest\"\x7f\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x16\n" +
	"\x14ListProvidersRequest\"H\n" +
	"\x15ListProvidersResponse\x12/\n" +
	"\tproviders\x18\x01 \x03(\v2\x11.mule.v1.ProviderR\tproviders\"\x1e\n" +
	"\bProvider\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14ListWorkflowsRequest\"H\n" +
	"\x15ListWorkflowsResponse\x12/\n" +
	"\tworkflows\x18\x01 \x03(\v2\x11.mule.v1.WorkflowR\tworkflows\"(\n" +
	"\x12GetWorkflowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"D\n" +
	"\x13GetWorkflowResponse\x12-\n" +
	"\bworkflow\x18\x01 \x01(\v2\x11.mule.v1.WorkflowR\bworkflow\"\xb9\x02\n" +
	"\bWorkflow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"is_default\x18\x04 \x01(\bR\tisDefault\x12+\n" +
	"\x05steps\x18\x05 \x03(\v2\x15.mule.v1.WorkflowStepR\x05steps\x121\n" +
	"\x14validation_functions\x18\x06 \x03(\tR\x13validationFunctions\x124\n" +
	"\btriggers\x18\a \x03(\v2\x18.mule.v1.TriggerSettingsR\btriggers\x122\n" +
	"\aoutputs\x18\b \x03(\v2\x18.mule.v1.TriggerSettingsR\aoutputs\"\xb7\x01\n" +
	"\fWorkflowStep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\x05R\aagentId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x03 \x01(\tR\tagentName\x12!\n" +
	"\foutput_field\x18\x04 \x01(\tR\voutputField\x12:\n" +
	"\vintegration\x18\x05 \x01(\v2\x18.mule.v1.TriggerSettingsR\vintegration\"\xb8\x01\n" +
	"\x0fTriggerSettings\x12 \n" +
	"\vintegration\x18\x01 \x01(\tR\vintegration\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x126\n" +
	"\x04data\x18\x03 \x03(\v2\".mule.v1.TriggerSettings.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x13\n" +
	"\x11ListAgentsRequest\"<\n" +
	"\x12ListAgentsResponse\x12&\n" +
	"\x06agents\x18\x01 \x03(\v2\x0e.mule.v1.AgentR\x06agents\"!\n" +
	"\x0fGetAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"8\n" +
	"\x10GetAgentResponse\x12$\n" +
	"\x05agent\x18\x01 \x01(\v2\x0e.mule.v1.AgentR\x05agent\"\x89\x02\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rprovider_name\x18\x03 \x01(\tR\fproviderName\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12'\n" +
	"\x0fprompt_template\x18\x05 \x01(\tR\x0epromptTemplate\x12#\n" +
	"\rsystem_prompt\x18\x06 \x01(\tR\fsystemPrompt\x12\x14\n" +
	"\x05tools\x18\a \x03(\tR\x05tools\x12=\n" +
	"\x0eudiff_settings\x18\b \x01(\v2\x16.mule.v1.UDiffSettingsR\rudiffSettings\")\n" +
	"\rUDiffSettings\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"\x1d\n" +
	"\x1bListRunningWorkflowsRequest\"e\n" +
	"\x1cListRunningWorkflowsResponse\x12E\n" +
	"\x11running_workflows\x18\x01 \x03(\v2\x18.mule.v1.RunningWorkflowR\x10runningWorkflows\"\x8f\x02\n" +
	"\x0fRunningWorkflow\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12#\n" +
	"\rworkflow_name\x18\x02 \x01(\tR\fworkflowName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12>\n" +
	"\fstep_results\x18\x05 \x03(\v2\x1b.mule.v1.WorkflowStepResultR\vstepResults\x12!\n" +
	"\fcurrent_step\x18\x06 \x01(\tR\vcurrentStep\"\xc3\x01\n" +
	"\x12WorkflowStepResult\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"i\n" +
	"\x16ExecuteWorkflowRequest\x12#\n" +
	"\rworkflow_name\x18\x01 \x01(\tR\fworkflowName\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"n\n" +
	"\x17ExecuteWorkflowResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x81\x05\n" +
	"\vMuleService\x12E\n" +
	"\fGetHeartbeat\x12\x19.mule.v1.HeartbeatRequest\x1a\x1a.mule.v1.HeartbeatResponse\x12N\n" +
	"\rListWorkflows\x12\x1d.mule.v1.ListWorkflowsRequest\x1a\x1e.mule.v1.ListWorkflowsResponse\x12H\n" +
	"\vGetWorkflow\x12\x1b.mule.v1.GetWorkflowRequest\x1a\x1c.mule.v1.GetWorkflowResponse\x12N\n" +
	"\rListProviders\x12\x1d.mule.v1.ListProvidersRequest\x1a\x1e.mule.v1.ListProvidersResponse\x12E\n" +
	"\n" +
	"ListAgents\x12\x1a.mule.v1.ListAgentsRequest\x1a\x1b.mule.v1.ListAgentsResponse\x12?\n" +
	"\bGetAgent\x12\x18.mule.v1.GetAgentRequest\x1a\x19.mule.v1.GetAgentResponse\x12c\n" +
	"\x14ListRunningWorkflows\x12$.mule.v1.ListRunningWorkflowsRequest\x1a%.mule.v1.ListRunningWorkflowsResponse\x12T\n" +
	"\x0fExecuteWorkflow\x12\x1f.mule.v1.ExecuteWorkflowRequest\x1a .mule.v1.ExecuteWorkflowResponseB#Z!github.com/mule-ai/mule/api/protob\x06proto3"

var (
	file_mule_proto_rawDescOnce sync.Once
	file_mule_proto_rawDescData []byte
)

func file_mule_proto_rawDescGZIP() []byte {
	file_mule_proto_rawDescOnce.Do(func() {
		file_mule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mule_proto_rawDesc), len(file_mule_proto_rawDesc)))
	})
	return file_mule_proto_rawDescData
}

var file_mule_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_mule_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),             // 0: mule.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),            // 1: mule.v1.HeartbeatResponse
	(*ListProvidersRequest)(nil),         // 2: mule.v1.ListProvidersRequest
	(*ListProvidersResponse)(nil),        // 3: mule.v1.ListProvidersResponse
	(*Provider)(nil),                     // 4: mule.v1.Provider
	(*ListWorkflowsRequest)(nil),         // 5: mule.v1.ListWorkflowsRequest
	(*ListWorkflowsResponse)(nil),        // 6: mule.v1.ListWorkflowsResponse
	(*GetWorkflowRequest)(nil),           // 7: mule.v1.GetWorkflowRequest
	(*GetWorkflowResponse)(nil),          // 8: mule.v1.GetWorkflowResponse
	(*Workflow)(nil),                     // 9: mule.v1.Workflow
	(*WorkflowStep)(nil),                 // 10: mule.v1.WorkflowStep
	(*TriggerSettings)(nil),              // 11: mule.v1.TriggerSettings
	(*ListAgentsRequest)(nil),            // 12: mule.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),           // 13: mule.v1.ListAgentsResponse
	(*GetAgentRequest)(nil),              // 14: mule.v1.GetAgentRequest
	(*GetAgentResponse)(nil),             // 15: mule.v1.GetAgentResponse
	(*Agent)(nil),                        // 16: mule.v1.Agent
	(*UDiffSettings)(nil),                // 17: mule.v1.UDiffSettings
	(*ListRunningWorkflowsRequest)(nil),  // 18: mule.v1.ListRunningWorkflowsRequest
	(*ListRunningWorkflowsResponse)(nil), // 19: mule.v1.ListRunningWorkflowsResponse
	(*RunningWorkflow)(nil),              // 20: mule.v1.RunningWorkflow
	(*WorkflowStepResult)(nil),           // 21: mule.v1.WorkflowStepResult
	(*ExecuteWorkflowRequest)(nil),       // 22: mule.v1.ExecuteWorkflowRequest
	(*ExecuteWorkflowResponse)(nil),      // 23: mule.v1.ExecuteWorkflowResponse
	nil,                                  // 24: mule.v1.TriggerSettings.DataEntry
	(*timestamppb.Timestamp)(nil),        // 25: google.protobuf.Timestamp
}
var file_mule_proto_depIdxs = []int32{
	25, // 0: mule.v1.HeartbeatResponse.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 1: mule.v1.ListProvidersResponse.providers:type_name -> mule.v1.Provider
	9,  // 2: mule.v1.ListWorkflowsResponse.workflows:type_name -> mule.v1.Workflow
	9,  // 3: mule.v1.GetWorkflowResponse.workflow:type_name -> mule.v1.Workflow
	10, // 4: mule.v1.Workflow.steps:type_name -> mule.v1.WorkflowStep
	11, // 5: mule.v1.Workflow.triggers:type_name -> mule.v1.TriggerSettings
	11, // 6: mule.v1.Workflow.outputs:type_name -> mule.v1.TriggerSettings
	11, // 7: mule.v1.WorkflowStep.integration:type_name -> mule.v1.TriggerSettings
	24, // 8: mule.v1.TriggerSettings.data:type_name -> mule.v1.TriggerSettings.DataEntry
	16, // 9: mule.v1.ListAgentsResponse.agents:type_name -> mule.v1.Agent
	16, // 10: mule.v1.GetAgentResponse.agent:type_name -> mule.v1.Agent
	17, // 11: mule.v1.Agent.udiff_settings:type_name -> mule.v1.UDiffSettings
	20, // 12: mule.v1.ListRunningWorkflowsResponse.running_workflows:type_name -> mule.v1.RunningWorkflow
	25, // 13: mule.v1.RunningWorkflow.started_at:type_name -> google.protobuf.Timestamp
	21, // 14: mule.v1.RunningWorkflow.step_results:type_name -> mule.v1.WorkflowStepResult
	25, // 15: mule.v1.WorkflowStepResult.completed_at:type_name -> google.protobuf.Timestamp
	0,  // 16: mule.v1.MuleService.GetHeartbeat:input_type -> mule.v1.HeartbeatRequest
	5,  // 17: mule.v1.MuleService.ListWorkflows:input_type -> mule.v1.ListWorkflowsRequest
	7,  // 18: mule.v1.MuleService.GetWorkflow:input_type -> mule.v1.GetWorkflowRequest
	2,  // 19: mule.v1.MuleService.ListProviders:input_type -> mule.v1.ListProvidersRequest
	12, // 20: mule.v1.MuleService.ListAgents:input_type -> mule.v1.ListAgentsRequest
	14, // 21: mule.v1.MuleService.GetAgent:input_type -> mule.v1.GetAgentRequest
	18, // 22: mule.v1.MuleService.ListRunningWorkflows:input_type -> mule.v1.ListRunningWorkflowsRequest
	22, // 23: mule.v1.MuleService.ExecuteWorkflow:input_type -> mule.v1.ExecuteWorkflowRequest
	1,  // 24: mule.v1.MuleService.GetHeartbeat:output_type -> mule.v1.HeartbeatResponse
	6,  // 25: mule.v1.MuleService.ListWorkflows:output_type -> mule.v1.ListWorkflowsResponse
	8,  // 26: mule.v1.MuleService.GetWorkflow:output_type -> mule.v1.GetWorkflowResponse
	3,  // 27: mule.v1.MuleService.ListProviders:output_type -> mule.v1.ListProvidersResponse
	13, // 28: mule.v1.MuleService.ListAgents:output_type -> mule.v1.ListAgentsResponse
	15, // 29: mule.v1.MuleService.GetAgent:output_type -> mule.v1.GetAgentResponse
	19, // 30: mule.v1.MuleService.ListRunningWorkflows:output_type -> mule.v1.ListRunningWorkflowsResponse
	23, // 31: mule.v1.MuleService.ExecuteWorkflow:output_type -> mule.v1.ExecuteWorkflowResponse
	24, // [24:32] is the sub-list for method output_type
	16, // [16:24] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_mule_proto_init() }
func file_mule_proto_init() {
	if File_mule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mule_proto_rawDesc), len(file_mule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mule_proto_goTypes,
		DependencyIndexes: file_mule_proto_depIdxs,
		MessageInfos:      file_mule_proto_msgTypes,
	}.Build()
	File_mule_proto = out.File
	file_mule_proto_goTypes = nil
	file_mule_proto_depIdxs = nil
}
